# Makefile: A standard Makefile for main.c

CFLAGS = -DPROF -O3 -Wall -Wextra -Wswitch-enum -std=c11 -pedantic -ggdb
LDLIBS = -lm -lpthread -lX11 -lXext
all  : main
clean:
	/bin/rm -rf main main.o
# END OF FILE
