# Makefile: A standard Makefile for main.c

CFLAGS = `pkg-config --cflags libavutil libavformat libswscale`
LDLIBS = `pkg-config --libs libavutil libavformat libswscale`

all  : main
clean:
	/bin/rm -rf main main.o 
# END OF FILE
